[versions]
agp = "7.4.2"
room = "2.5.0"

# TODO: Update both versions here ↓
kotlin = "1.8.10"      # "1.8.20-RC"
ksp = "1.8.10-1.0.9"   # "1.8.20-RC-1.0.9"
# TODO: Update both version here ↑

[libraries]
room = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
